# Generated by Django 5.0.4 on 2024-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
